apiVersion: accelerator.apps.tanzu.vmware.com/v1alpha1
kind: Accelerator
metadata:
  name: spring-sensors-rabbit-dodd
  namespace: accelerator-system
spec:
  git:
    ref:
      branch: accelerator
    url: https://github.com/doddatpivotal/spring-sensors